markdown: kramdown

t:
  es:
    empresa_name: 'Empresa'
    contacto_name: 'Contacto'
    login_name: 'Iniciar sesión'
    sabermas_name: 'Quiero saber más'
    sumate_name: 'Súmate'
    donde_encontrar_name: 'Dónde puedes encontrar este plan'
    agenda_tour_name: 'Agenda un tour'
    selecciona_ubicacion_name: 'Seleccionar Ubicación'
    agendar_name: 'Agendar'

    ubicaciones_name: 'Ubicaciones'
    ubicaciones_url: '/ubicaciones/'
    planes_name: 'Planes'
    planes_url: '/planes/'
    alianzas_name: 'Alianzas'
    alianzas_url: '/alianzas/'
    eventos_name: 'Eventos'
    eventos_url: '/eventos/'
    prensa_name: 'Prensa'
    prensa_url: '/prensa/'
    porque_name: '¿Porqué Edge?'
    porque_url: '/porque-edge/'
    preguntas_name: 'Preguntas frecuentes'
    preguntas_url: '/preguntas-frecuentes/'
    terminos_name: 'Términos y condiciones'
    terminos_url: '/terminos-y-condiciones/'
  en:
    empresa_name: 'Company'
    contacto_name: 'Contact'
    login_name: 'Login'
    sabermas_name: 'I want to know more'
    sumate_name: 'Join'
    donde_encontrar_name: 'Where can I find this plan'
    agenda_tour_name: 'Book a tour'
    selecciona_ubicacion_name: 'Choose a location'
    agendar_name: 'Book'

    ubicaciones_name: 'Locations'
    ubicaciones_url: '/locations/'
    planes_name: 'Plans'
    planes_url: '/plans/'
    alianzas_name: 'Alliances'
    alianzas_url: '/alliances/'
    eventos_name: 'Events'
    eventos_url: '/events/'
    prensa_name: 'Press'
    prensa_url: '/press/'
    porque_name: 'Why Edge?'
    porque_url: '/why-edge/'
    preguntas_name: 'FAQ'
    preguntas_url: '/faq/'
    terminos_name: 'Terms of service'
    terminos_url: '/terms-of-service/'
